//! Compiles `data/commands.ron` and `data/functions.ron` into static tables.
//!
//! Design 02 decision D3: the command grammar is table-driven from a declarative
//! data file, so adding a command means editing data rather than the parser, and
//! the same table is the single source of truth for abbreviation, completion
//! (spec §22) and help.
//!
//! # Why there is a RON reader in here instead of a `ron` build-dependency
//!
//! `crates/stratum-parse/Cargo.toml` is W04's file (R0), and a `[build-
//! dependencies]` section would also need `ron` and `serde` in the workspace
//! dependency table, which is W00's. The subset actually used by these two data
//! files — named-field structs, lists, strings, integers and booleans — is a
//! ~130-line recursive-descent reader, and it VALIDATES the file rather than
//! trusting it: an unknown field name or a misspelled flag fails the build with
//! a line number instead of silently producing a command with no options.
//!
//! # Why the generated table is a sorted array and not a `phf` map
//!
//! 02 §6.3 specifies `phf` for the exact-hit map plus a sorted array for prefix
//! resolution. `CommandTable::resolve` (W04, `cmdsig.rs`) already resolves both
//! exact hits and abbreviations out of ONE sorted array, with a first-byte
//! compare that measured 16 ns per lookup — once per region of the document.
//! A `phf` map alongside it would be a second copy of the same keys to keep in
//! sync for no measurable gain, and would pull two crates into a wasm build.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=data/commands.ron");
    println!("cargo:rerun-if-changed=data/functions.ron");
    println!("cargo:rerun-if-changed=build.rs");

    let out = std::env::var("OUT_DIR").expect("OUT_DIR");
    let mut src = String::new();
    src.push_str("// @generated by build.rs from data/*.ron — do not edit.\n");
    emit_commands(&mut src);
    emit_functions(&mut src);
    std::fs::write(Path::new(&out).join("cmdtable_generated.rs"), src).expect("write generated");
}

// ───────────────────────────── commands ─────────────────────────────────────

fn emit_commands(src: &mut String) {
    let text = std::fs::read_to_string("data/commands.ron").expect("read data/commands.ron");
    let root = parse(&text, "data/commands.ron");
    let rows = root.field("commands").list();

    // Option lists are deduplicated by content: `[if] [in]`-shaped commands
    // share option sets constantly, and one static per distinct set keeps the
    // generated file from being mostly identical arrays.
    let mut opt_sets: BTreeMap<String, usize> = BTreeMap::new();
    let mut opt_bodies: Vec<String> = Vec::new();
    let mut out_rows: Vec<(String, String)> = Vec::new();

    for row in rows {
        let name = row.field("name").string();
        let abbrev = row.field("abbrev").int();
        assert!(
            abbrev == 0 || (abbrev as usize) <= name.chars().count(),
            "{name}: min_abbrev {abbrev} exceeds the name length"
        );
        let slots = bits(
            "SlotMask",
            &row.opt("slots").map_or(String::new(), Value::string),
        );
        let weights = bits(
            "WeightMask",
            &row.opt("weights").map_or(String::new(), Value::string),
        );
        let flags = bits(
            "CmdFlags",
            &row.opt("flags").map_or(String::new(), Value::string),
        );
        let tier = tier(&row.field("tier").string());
        let help = row.field("help").string();

        let mut body = String::new();
        let mut opts: Vec<(String, String)> = Vec::new();
        if let Some(list) = row.opt("options") {
            for o in list.list() {
                let oname = o.field("name").string();
                let oabbrev = o.field("abbrev").int();
                assert!(
                    oabbrev == 0 || (oabbrev as usize) <= oname.chars().count(),
                    "{name}/{oname}: min_abbrev {oabbrev} exceeds the name length"
                );
                let arg = arg_kind(&o.field("arg").string());
                // 02 §6.1: "`nooption` is always accepted as the negation of
                // `option`." So negatable DEFAULTS TO TRUE and the data file
                // only ever spells it out to turn it off.
                let neg = o.opt("neg").is_none_or(Value::bool);
                opts.push((
                    oname.clone(),
                    format!(
                        "    OptionSpec {{ canonical: {oname:?}, min_abbrev: {oabbrev}, \
                         arg: OptionArgKind::{arg}, negatable: {neg} }},\n"
                    ),
                ));
            }
        }
        // Sorted by canonical: `CommandSig::options` is documented as sorted and
        // option resolution binary-searches it.
        opts.sort_by(|a, b| a.0.cmp(&b.0));
        for w in opts.windows(2) {
            assert_ne!(w[0].0, w[1].0, "{name}: duplicate option {}", w[0].0);
        }
        for (_, line) in &opts {
            body.push_str(line);
        }
        let idx = *opt_sets.entry(body.clone()).or_insert_with(|| {
            opt_bodies.push(body.clone());
            opt_bodies.len() - 1
        });

        out_rows.push((
            name.clone(),
            format!(
                "    CommandSig {{ canonical: {name:?}, min_abbrev: {abbrev}, slots: {slots}, \
                 weights: {weights}, options: OPTS_{idx}, flags: {flags}, tier: Tier::{tier}, \
                 help: {help:?} }},\n"
            ),
        ));
    }

    out_rows.sort_by(|a, b| a.0.cmp(&b.0));
    for w in out_rows.windows(2) {
        assert_ne!(w[0].0, w[1].0, "duplicate command {}", w[0].0);
    }

    for (i, body) in opt_bodies.iter().enumerate() {
        let _ = write!(src, "static OPTS_{i}: &[OptionSpec] = &[\n{body}];\n");
    }
    src.push_str("/// Every command signature, sorted by `canonical`.\npub static COMMANDS: &[CommandSig] = &[\n");
    for (_, line) in &out_rows {
        src.push_str(line);
    }
    src.push_str("];\n");
}

fn bits(ty: &str, spec: &str) -> String {
    let spec = spec.trim();
    if spec.is_empty() {
        return format!("{ty}::empty()");
    }
    spec.split('|')
        .map(|p| format!("{ty}::{}", p.trim()))
        .collect::<Vec<_>>()
        .join(".union(")
        + &")".repeat(spec.split('|').count() - 1)
}

fn tier(s: &str) -> &'static str {
    match s {
        "V1" => "V1",
        "V1_5" => "V1_5",
        "V2" => "V2",
        _ => panic!("unknown tier {s:?}"),
    }
}

fn arg_kind(s: &str) -> &'static str {
    match s {
        "None" => "None",
        "Int" => "Int",
        "Real" => "Real",
        "Str" => "Str",
        "Numlist" => "Numlist",
        "Varlist" => "Varlist",
        "Exprs" => "Exprs",
        "Fmt" => "Fmt",
        "Raw" => "Raw",
        _ => panic!("unknown option arg kind {s:?}"),
    }
}

// ───────────────────────────── functions ────────────────────────────────────

fn emit_functions(src: &mut String) {
    let text = std::fs::read_to_string("data/functions.ron").expect("read data/functions.ron");
    let root = parse(&text, "data/functions.ron");
    let mut rows: Vec<(String, String)> = Vec::new();
    for f in root.field("functions").list() {
        let name = f.field("name").string();
        let min = f.field("min").int();
        let max = f.field("max").int();
        assert!(max >= min, "{name}: max arity below min");
        let ret = match f.field("ret").string().as_str() {
            "Real" => "Real",
            "Str" => "Str",
            "Either" => "Either",
            other => panic!("unknown return type {other:?}"),
        };
        // A function is IMPURE when two calls with the same arguments may differ:
        // the random generators, and nothing else in v1. `stratum-intel` reads
        // this to decide whether a region can be cached (spec §12).
        let deterministic = f.opt("random").is_none_or(|v| !v.bool());
        let tier = tier(&f.field("tier").string());
        rows.push((
            name.clone(),
            format!(
                "    FnSig {{ name: {name:?}, min_args: {min}, max_args: {max}, \
                 ret: FnRet::{ret}, deterministic: {deterministic}, tier: Tier::{tier} }},\n"
            ),
        ));
    }
    rows.sort_by(|a, b| a.0.cmp(&b.0));
    for w in rows.windows(2) {
        assert_ne!(w[0].0, w[1].0, "duplicate function {}", w[0].0);
    }
    src.push_str(
        "/// Every function signature, sorted by `name`.\npub static FUNCTIONS: &[FnSig] = &[\n",
    );
    for (_, line) in &rows {
        src.push_str(line);
    }
    src.push_str("];\n");
}

// ─────────────────────── the restricted RON reader ──────────────────────────

#[derive(Clone, Debug)]
enum Value {
    Struct(Vec<(String, Value)>),
    List(Vec<Value>),
    Str(String),
    Int(i64),
    Bool(bool),
}

impl Value {
    fn field(&self, name: &str) -> &Value {
        self.opt(name)
            .unwrap_or_else(|| panic!("missing required field `{name}`"))
    }

    fn opt(&self, name: &str) -> Option<&Value> {
        match self {
            Value::Struct(f) => f.iter().find(|(k, _)| k == name).map(|(_, v)| v),
            _ => panic!("expected a struct"),
        }
    }

    fn list(&self) -> &[Value] {
        match self {
            Value::List(v) => v,
            _ => panic!("expected a list"),
        }
    }

    fn string(&self) -> String {
        match self {
            Value::Str(s) => s.clone(),
            _ => panic!("expected a string"),
        }
    }

    fn int(&self) -> i64 {
        match self {
            Value::Int(i) => *i,
            _ => panic!("expected an integer"),
        }
    }

    fn bool(&self) -> bool {
        match self {
            Value::Bool(b) => *b,
            _ => panic!("expected a boolean"),
        }
    }
}

struct Reader<'a> {
    b: &'a [u8],
    i: usize,
    file: &'a str,
}

fn parse(text: &str, file: &str) -> Value {
    let mut r = Reader {
        b: text.as_bytes(),
        i: 0,
        file,
    };
    let v = r.value();
    r.ws();
    assert!(r.i >= r.b.len(), "{}: trailing junk at byte {}", file, r.i);
    v
}

impl Reader<'_> {
    fn line(&self) -> usize {
        self.b[..self.i].iter().filter(|c| **c == b'\n').count() + 1
    }

    fn ws(&mut self) {
        loop {
            while self.i < self.b.len() && self.b[self.i].is_ascii_whitespace() {
                self.i += 1;
            }
            if self.b[self.i..].starts_with(b"//") {
                while self.i < self.b.len() && self.b[self.i] != b'\n' {
                    self.i += 1;
                }
                continue;
            }
            if self.b[self.i..].starts_with(b"/*") {
                self.i += 2;
                while self.i < self.b.len() && !self.b[self.i..].starts_with(b"*/") {
                    self.i += 1;
                }
                self.i = (self.i + 2).min(self.b.len());
                continue;
            }
            return;
        }
    }

    fn value(&mut self) -> Value {
        self.ws();
        match self.b.get(self.i) {
            Some(b'(') => self.strct(),
            Some(b'[') => self.list(),
            Some(b'"') => Value::Str(self.string()),
            Some(c) if c.is_ascii_digit() || *c == b'-' => self.int(),
            Some(_) => {
                let w = self.ident();
                match w.as_str() {
                    "true" => Value::Bool(true),
                    "false" => Value::Bool(false),
                    other => panic!("{}:{}: unexpected `{other}`", self.file, self.line()),
                }
            }
            None => panic!("{}: unexpected end of file", self.file),
        }
    }

    fn strct(&mut self) -> Value {
        self.i += 1;
        let mut fields = Vec::new();
        loop {
            self.ws();
            if self.b.get(self.i) == Some(&b')') {
                self.i += 1;
                return Value::Struct(fields);
            }
            let key = self.ident();
            assert!(
                !key.is_empty(),
                "{}:{}: expected a field name",
                self.file,
                self.line()
            );
            self.ws();
            assert_eq!(
                self.b.get(self.i),
                Some(&b':'),
                "{}:{}: expected `:` after `{key}`",
                self.file,
                self.line()
            );
            self.i += 1;
            let v = self.value();
            fields.push((key, v));
            self.ws();
            if self.b.get(self.i) == Some(&b',') {
                self.i += 1;
            }
        }
    }

    fn list(&mut self) -> Value {
        self.i += 1;
        let mut items = Vec::new();
        loop {
            self.ws();
            if self.b.get(self.i) == Some(&b']') {
                self.i += 1;
                return Value::List(items);
            }
            items.push(self.value());
            self.ws();
            if self.b.get(self.i) == Some(&b',') {
                self.i += 1;
            }
        }
    }

    fn string(&mut self) -> String {
        self.i += 1;
        let start = self.i;
        while self.i < self.b.len() && self.b[self.i] != b'"' {
            assert_ne!(
                self.b[self.i],
                b'\\',
                "{}:{}: escapes are not supported in this reader",
                self.file,
                self.line()
            );
            self.i += 1;
        }
        let s = String::from_utf8(self.b[start..self.i].to_vec()).expect("utf-8");
        self.i += 1;
        s
    }

    fn int(&mut self) -> Value {
        let start = self.i;
        if self.b[self.i] == b'-' {
            self.i += 1;
        }
        while self.i < self.b.len() && self.b[self.i].is_ascii_digit() {
            self.i += 1;
        }
        Value::Int(
            std::str::from_utf8(&self.b[start..self.i])
                .expect("utf-8")
                .parse()
                .expect("integer"),
        )
    }

    fn ident(&mut self) -> String {
        let start = self.i;
        while self.i < self.b.len()
            && (self.b[self.i].is_ascii_alphanumeric() || self.b[self.i] == b'_')
        {
            self.i += 1;
        }
        String::from_utf8(self.b[start..self.i].to_vec()).expect("utf-8")
    }
}
