//! `Dataset::into_frame` acceptance: the bridge is lossless, zero-copy where
//! it claims to be, and loud where the engine cannot hold a fact.
//!
//! The round-trip criterion is [`canonical_eq`] — byte identity against a
//! Stata-written fixture is impossible by design (`04` §11.3: uninitialised
//! padding, unobservable strL coalescing). But between two files **this
//! writer** produced from canonically equal datasets, byte identity *is*
//! achievable, and asserting it is the strongest available proof that the
//! bridge dropped nothing: `write(original)` and
//! `write(from_frame(into_frame(original)))` must be the same bytes.
//!
//! Fixtures are the committed `tests/fixtures/dta/` set (W03's, generated by
//! `make_fixtures.do`; never regenerated — the Stata licence has expired).

use std::path::PathBuf;

use stratum_dta::{
    byte_diff, canonical_eq, read_dta, read_dta_bytes, write_dta_to_vec, Dataset, DtaColumn,
    DtaError, DtaReadOptions, DtaVar, DtaWriteOptions, Release, StrLData,
};

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures/dta")
        .join(name)
}

/// read → into_frame → from_frame → write, asserting canonical equality at
/// every hop and byte identity between the two writes we control.
fn round_trip(name: &str) {
    let ds0 = read_dta(fixture(name)).unwrap_or_else(|e| panic!("{name}: read: {e}"));
    let bridge = ds0
        .clone()
        .into_frame("default")
        .unwrap_or_else(|e| panic!("{name}: into_frame: {e}"));
    assert_eq!(
        bridge.timestamp, ds0.timestamp,
        "{name}: the timestamp must come back through the bridge"
    );
    assert!(
        !bridge.frame.changed(),
        "{name}: a freshly loaded frame is in sync with its file"
    );

    let mut ds1 = Dataset::from_frame(&bridge.frame, ds0.release)
        .unwrap_or_else(|e| panic!("{name}: from_frame: {e}"));
    // The one fact a `Frame` has no slot for, restored from the bridge.
    ds1.timestamp = bridge.timestamp;
    canonical_eq(&ds0, &ds1).unwrap_or_else(|d| panic!("{name}: after the bridge: {d}"));

    let opts = DtaWriteOptions::default();
    let b0 = write_dta_to_vec(&ds0, &opts).unwrap_or_else(|e| panic!("{name}: write ds0: {e}"));
    let b1 = write_dta_to_vec(&ds1, &opts).unwrap_or_else(|e| panic!("{name}: write ds1: {e}"));
    let d = byte_diff(&b0, &b1);
    assert_eq!(
        d.count, 0,
        "{name}: writing the bridged dataset must be byte-identical to writing the original: {d}"
    );

    let ds2 = read_dta_bytes(&b1, &DtaReadOptions::default())
        .unwrap_or_else(|e| panic!("{name}: re-read: {e}"));
    canonical_eq(&ds0, &ds2).unwrap_or_else(|d| panic!("{name}: after write+read: {d}"));
}

#[test]
fn auto_round_trips_through_a_frame() {
    round_trip("auto.dta");
}

#[test]
fn alltypes_round_trips_through_a_frame() {
    round_trip("alltypes.dta");
}

#[test]
fn strl_round_trips_through_a_frame() {
    round_trip("strl.dta");
}

#[test]
fn sorted_round_trips_through_a_frame() {
    round_trip("sorted.dta");
}

#[test]
fn empty_round_trips_through_a_frame() {
    round_trip("empty.dta");
}

#[test]
fn wide_round_trips_through_a_frame() {
    round_trip("wide.dta");
}

/// The zero-copy claim, asserted on identity rather than on a clock (ADR-017):
/// the chunk a fixed-width column was transposed into IS the chunk the frame
/// serves reads from.
#[test]
fn fixed_columns_move_into_the_frame_without_a_copy() {
    let ds = read_dta(fixture("auto.dta")).expect("auto.dta reads");
    let i = ds.index_of("price").expect("auto.dta has price");
    let before = match &ds.cols[i] {
        DtaColumn::Fixed(stratum_data::Column::Int(c)) => c.chunk(0).as_ptr(),
        other => panic!("price is int in auto.dta, got {:?}", other.storage_type()),
    };
    let bridge = ds.into_frame("default").expect("auto.dta bridges");
    let idx = bridge.frame.index_of("price").expect("price survived");
    let after = match bridge.frame.col(idx).expect("column exists") {
        stratum_data::Column::Int(c) => c.chunk(0).as_ptr(),
        other => panic!("price stayed int, got {:?}", other.storage_type()),
    };
    assert_eq!(before, after, "the column was copied, not moved");
}

/// Everything `alltypes.dta` carries beyond the cells: formats, labels,
/// value-label attachment and table, dataset label, characteristics, notes.
#[test]
fn alltypes_metadata_lands_in_the_frame() {
    let ds = read_dta(fixture("alltypes.dta")).expect("alltypes.dta reads");
    let bridge = ds.into_frame("default").expect("alltypes.dta bridges");
    let f = &bridge.frame;

    assert_eq!(f.label(), "All storage types fixture");
    let dbl = f.index_of("v_double").expect("v_double exists");
    let v = f.var(dbl).expect("metadata exists");
    assert_eq!(stratum_data::variable::format_string(&v.format), "%12.4f");
    assert!(v.label.starts_with("A double with a deliberately long"));

    let byte = f.index_of("v_byte").expect("v_byte exists");
    let v = f.var(byte).expect("metadata exists");
    assert_eq!(v.value_label.as_deref(), Some("yesno"));
    let table = f.labels().get("yesno").expect("the table crossed too");
    assert_eq!(table.get(1.0), Some("Yes"));
    assert_eq!(table.get(-1.0), Some("Negative"));

    assert_eq!(
        f.chars().get("_dta", "source"),
        Some("make_fixtures.do"),
        "characteristics cross verbatim"
    );
    assert_eq!(f.chars().get("v_byte", "units"), Some("arbitrary"));
    assert_eq!(
        f.chars().notes("_dta"),
        vec!["this fixture exercises every Stata storage type"]
    );
}

/// The `.dta` sortlist is recorded, not re-proven: the frame claims the order
/// without permuting a single row.
#[test]
fn sorted_dta_records_its_sortlist_without_permuting() {
    let ds = read_dta(fixture("sorted.dta")).expect("sorted.dta reads");
    assert_eq!(ds.sorted_by(), vec!["foreign", "price"], "fixture pin");
    let bridge = ds.into_frame("default").expect("sorted.dta bridges");
    let f = &bridge.frame;
    let sort = f.sort_state();
    assert!(
        sort.valid,
        "the file's claim is trusted, as Stata trusts it"
    );
    let names: Vec<&str> = sort
        .keys
        .iter()
        .map(|k| &*f.var(*k).expect("key names a variable").name)
        .collect();
    assert_eq!(names, vec!["foreign", "price"]);
}

/// `empty.dta`: one variable, zero observations.
#[test]
fn empty_dta_bridges_with_zero_observations() {
    let ds = read_dta(fixture("empty.dta")).expect("empty.dta reads");
    let bridge = ds.into_frame("default").expect("empty.dta bridges");
    assert_eq!(bridge.frame.n_obs(), 0);
    assert_eq!(bridge.frame.n_vars(), 1);
    assert!(bridge.frame.index_of("novalues").is_some());
}

/// The strL binary flag (GSO type 129 vs 130) survives both directions. The
/// committed fixtures hold only text strLs — Stata's `replace` cannot plant a
/// blob — so the binary case is a built dataset.
#[test]
fn strl_binary_flags_survive_the_bridge_both_ways() {
    let mut s = StrLData::with_capacity(3, 32);
    s.push(b"plain text", false);
    s.push(b"\x00\xffblob", true);
    s.push(b"", false);
    let mut ds = Dataset::new(Release::R118);
    ds.push_var(
        DtaVar::new("payload", stratum_core::StorageType::StrL),
        DtaColumn::StrL(s),
    )
    .expect("consistent");

    let bridge = ds.clone().into_frame("default").expect("bridges");
    let ds1 = Dataset::from_frame(&bridge.frame, Release::R118).expect("projects back");
    canonical_eq(&ds, &ds1).expect("bytes and binary flags identical");
    let col = ds1.col("payload").expect("payload survived");
    assert!(!col.is_binary(0) && col.is_binary(1) && !col.is_binary(2));
}

/// A value-label attachment naming a table the file does not define is kept
/// verbatim — the read already warned; dropping it here would erase what
/// `save` must write back.
#[test]
fn a_dangling_value_label_attachment_is_kept_verbatim() {
    let mut ds = Dataset::new(Release::R118);
    let mut var = DtaVar::new("x", stratum_core::StorageType::Byte);
    var.value_label = Some("ghost".to_owned());
    ds.push_var(
        var,
        DtaColumn::Fixed(stratum_data::Column::new_missing(
            stratum_core::StorageType::Byte,
            2,
        )),
    )
    .expect("consistent");
    let bridge = ds.into_frame("default").expect("bridges");
    let idx = bridge.frame.index_of("x").expect("x exists");
    assert_eq!(
        bridge
            .frame
            .var(idx)
            .expect("metadata")
            .value_label
            .as_deref(),
        Some("ghost")
    );
}

// ---------------------------------------------------------------------------
// The refusals: every loss point is a typed error, never a silent drop.
// ---------------------------------------------------------------------------

fn byte_var(name: &str, rows: u64) -> (DtaVar, DtaColumn) {
    (
        DtaVar::new(name, stratum_core::StorageType::Byte),
        DtaColumn::Fixed(stratum_data::Column::new_missing(
            stratum_core::StorageType::Byte,
            rows,
        )),
    )
}

#[test]
fn a_name_the_frame_refuses_is_a_typed_error_not_a_rename() {
    // The reader keeps `9lives` verbatim (with a warning); the bridge must
    // refuse it loudly rather than guess a rename.
    let mut ds = Dataset::new(Release::R118);
    let (var, col) = byte_var("9lives", 1);
    ds.push_var(var, col)
        .expect("push_var does not validate names");
    match ds.into_frame("default") {
        Err(DtaError::FrameVar {
            index: 0,
            name,
            source,
        }) => {
            assert_eq!(name, "9lives");
            assert!(matches!(source, stratum_data::FrameError::InvalidName(_)));
        }
        other => panic!("expected FrameVar/InvalidName, got {other:?}"),
    }
}

#[test]
fn a_duplicate_name_is_a_typed_error() {
    let mut ds = Dataset::new(Release::R118);
    let (var, col) = byte_var("twin", 1);
    ds.push_var(var, col).expect("first is fine");
    let (var, col) = byte_var("twin", 1);
    ds.push_var(var, col)
        .expect("push_var does not check duplicates");
    match ds.into_frame("default") {
        Err(DtaError::FrameVar {
            index: 1,
            name,
            source,
        }) => {
            assert_eq!(name, "twin");
            assert!(matches!(source, stratum_data::FrameError::Duplicate(_)));
        }
        other => panic!("expected FrameVar/Duplicate, got {other:?}"),
    }
}

#[test]
fn a_format_that_does_not_survive_parsing_is_a_typed_error() {
    let mut ds = Dataset::new(Release::R118);
    let (mut var, col) = byte_var("x", 1);
    // `%tdD_m_Y` is a spelling Stata writes; the engine's parser rejects the
    // detail string rather than dropping it (stratum-core fmt), and the bridge
    // reports rather than guessing.
    var.format = "%tdD_m_Y".to_owned();
    ds.push_var(var, col).expect("consistent");
    match ds.into_frame("default") {
        Err(DtaError::FrameFormat {
            index: 0,
            name,
            format,
            ..
        }) => {
            assert_eq!((name.as_str(), format.as_str()), ("x", "%tdD_m_Y"));
        }
        other => panic!("expected FrameFormat, got {other:?}"),
    }
}

#[test]
fn a_sortlist_entry_naming_no_variable_is_a_typed_error() {
    let mut ds = Dataset::new(Release::R118);
    let (var, col) = byte_var("x", 1);
    ds.push_var(var, col).expect("consistent");
    ds.sortlist = vec![7];
    match ds.into_frame("default") {
        Err(DtaError::FrameSort { entry: 7 }) => {}
        other => panic!("expected FrameSort, got {other:?}"),
    }
}

#[test]
fn a_ragged_dataset_is_a_typed_error() {
    let mut ds = Dataset::new(Release::R118);
    let (var, col) = byte_var("x", 3);
    ds.push_var(var, col).expect("consistent");
    // Bypass `push_var`'s check through the public fields.
    let (var, col) = byte_var("y", 2);
    ds.vars.push(var);
    ds.cols.push(col);
    assert!(matches!(
        ds.into_frame("default"),
        Err(DtaError::Inconsistent(_))
    ));
}
